# Generated by Django 5.2.5 on 2025-08-26 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniQMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qms_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('department', models.CharField(choices=[('QA', 'Quality Assurance'), ('QC', 'Quality Control'), ('PD', 'Production'), ('TT', 'Technology Transfer'), ('PM', 'Project Management'), ('HR', 'Human Resources'), ('SH', 'Safety, Health and Environment'), ('FD', 'Formulations Research and Development'), ('AM', 'Administration'), ('FN', 'Finance'), ('BD', 'Business Development'), ('EN', 'Engineering'), ('WH', 'Warehouse'), ('PK', 'Packaging Development'), ('RA', 'Regulatory Affairs'), ('IT', 'Information and Technology'), ('SC', 'Supply Chain Management'), ('DA', 'Developmental Quality Assurance'), ('AD', 'Analytical Research and Development'), ('IP', 'Intellectual Property'), ('MK', 'Marketing'), ('PP', 'Production Planning and Inventory Control')], max_length=5)),
                ('actual_target_date', models.DateField()),
                ('proposed_target_date', models.DateField()),
            ],
            options={
                'ordering': ['proposed_target_date'],
            },
        ),
        migrations.CreateModel(
            name='MiniAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qms_number', models.CharField(max_length=20, unique=True)),
                ('initiated_date', models.DateField()),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('CAPA', 'CAPA'), ('PC', 'PC'), ('TC', 'TC'), ('DR', 'DR'), ('OSS', 'OSS'), ('OOT', 'OOT'), ('GI', 'GI'), ('LIR', 'LIR')], max_length=10)),
                ('target_date', models.DateField()),
                ('department', models.CharField(choices=[('QA', 'Quality Assurance'), ('QC', 'Quality Control'), ('PD', 'Production'), ('TT', 'Technology Transfer'), ('PM', 'Project Management'), ('HR', 'Human Resources'), ('SH', 'Safety, Health and Environment'), ('FD', 'Formulations Research and Development'), ('AM', 'Administration'), ('FN', 'Finance'), ('BD', 'Business Development'), ('EN', 'Engineering'), ('WH', 'Warehouse'), ('PK', 'Packaging Development'), ('RA', 'Regulatory Affairs'), ('IT', 'Information and Technology'), ('SC', 'Supply Chain Management'), ('DA', 'Developmental Quality Assurance'), ('AD', 'Analytical Research and Development'), ('IP', 'Intellectual Property'), ('MK', 'Marketing'), ('PP', 'Production Planning and Inventory Control')], max_length=5)),
                ('background', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Physical copy available at', max_length=255)),
            ],
            options={
                'ordering': ['target_date'],
                'indexes': [models.Index(fields=['qms_number'], name='qms_app_qms_qms_num_b404ae_idx'), models.Index(fields=['target_date'], name='qms_app_qms_target__6c777e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_plan', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('department', models.CharField(choices=[('QA', 'Quality Assurance'), ('QC', 'Quality Control'), ('PD', 'Production'), ('TT', 'Technology Transfer'), ('PM', 'Project Management'), ('HR', 'Human Resources'), ('SH', 'Safety, Health and Environment'), ('FD', 'Formulations Research and Development'), ('AM', 'Administration'), ('FN', 'Finance'), ('BD', 'Business Development'), ('EN', 'Engineering'), ('WH', 'Warehouse'), ('PK', 'Packaging Development'), ('RA', 'Regulatory Affairs'), ('IT', 'Information and Technology'), ('SC', 'Supply Chain Management'), ('DA', 'Developmental Quality Assurance'), ('AD', 'Analytical Research and Development'), ('IP', 'Intellectual Property'), ('MK', 'Marketing'), ('PP', 'Production Planning and Inventory Control')], max_length=5)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('qms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='qms_app.qms')),
            ],
            options={
                'ordering': ['target_date'],
                'indexes': [models.Index(fields=['target_date'], name='qms_app_act_target__f03fd5_idx')],
            },
        ),
    ]
