# Generated by Django 5.2.5 on 2025-08-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0002_miniqms_status_qms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='miniqms',
            name='type',
            field=models.CharField(blank=True, choices=[('CAPA', 'CAPA'), ('PC', 'PC'), ('TC', 'TC'), ('DR', 'DR'), ('OSS', 'OSS'), ('OOT', 'OOT'), ('GI', 'GI'), ('LIR', 'LIR')], max_length=10),
        ),
    ]
