# Generated by Django 5.2.5 on 2025-09-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0003_miniqms_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qms',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='qms_pdfs/', verbose_name='Attach PDF'),
        ),
    ]
