# Generated by Django 5.2.5 on 2025-09-14 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0004_qms_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniqms',
            name='type',
            field=models.CharField(blank=True, choices=[('CAPA', 'CAPA'), ('PC', 'PC'), ('TC', 'TC'), ('DR', 'DR'), ('OOS', 'OOS'), ('OOT', 'OOT'), ('GI', 'GI'), ('LIR', 'LIR')], max_length=10),
        ),
        migrations.AlterField(
            model_name='qms',
            name='type',
            field=models.CharField(choices=[('CAPA', 'CAPA'), ('PC', 'PC'), ('TC', 'TC'), ('DR', 'DR'), ('OOS', 'OOS'), ('OOT', 'OOT'), ('GI', 'GI'), ('LIR', 'LIR')], max_length=10),
        ),
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qms_number', models.CharField(max_length=20, verbose_name='QMS Number')),
                ('comments', models.TextField()),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='update_requests/', verbose_name='Attach File (Optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
