# Generated by Django 5.2.5 on 2025-11-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0005_alter_miniqms_type_alter_qms_type_updaterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qms',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('CFT', 'CFT'), ('EM', 'EM')], default='Open', max_length=10),
        ),
    ]
