# Generated by Django 5.2.5 on 2026-01-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0006_alter_qms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qms',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
