# Generated by Django 5.2.5 on 2026-02-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0007_qms_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='qms',
            name='involved_departments',
            field=models.ManyToManyField(blank=True, related_name='qms_records', to='qms_app.department'),
        ),
    ]
