# Generated by Django 6.0.3 on 2026-03-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0008_department_qms_involved_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='qms',
            name='review_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
