# Generated by Django 6.0.3 on 2026-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms_app', '0009_qms_review_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(choices=[('QA', 'Quality Assurance'), ('QC', 'Quality Control'), ('PD', 'Production'), ('TT', 'Technology Transfer'), ('PM', 'Project Management'), ('HR', 'Human Resources'), ('SH', 'Safety, Health and Environment'), ('FD', 'Formulations Research and Development'), ('AM', 'Administration'), ('FN', 'Finance'), ('BD', 'Business Development'), ('EN', 'Engineering'), ('WH', 'Warehouse'), ('PK', 'Packaging Development'), ('RA', 'Regulatory Affairs'), ('IT', 'Information and Technology'), ('SC', 'Supply Chain Management'), ('DA', 'Developmental Quality Assurance'), ('AD', 'Analytical Research and Development'), ('IP', 'Intellectual Property'), ('MK', 'Marketing'), ('PP', 'Production Planning and Inventory Control')], max_length=5, unique=True)),
                ('to_emails', models.TextField(help_text="Comma-separated email addresses for 'To' field")),
                ('cc_emails', models.TextField(blank=True, help_text="Comma-separated email addresses for 'CC' field")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department Email Config',
                'verbose_name_plural': 'Department Email Configs',
            },
        ),
    ]
